
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.*;
import javax.swing.JButton;
import javax.swing.JFrame;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */

public class Add_Candidate extends javax.swing.JFrame {

    /**
     * Creates new form Details
     */
    public Add_Candidate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */String dir;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        post = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cd1 = new javax.swing.JButton();
        cd2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Cls = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1386, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 260, 110));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton2.setText("Main Screen");
        jButton2.setToolTipText("MAIN SCREEN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 280, 60));

        name.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        name.setToolTipText("NAME OF CANDIDATE");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 420, 60));

        ID.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        ID.setToolTipText("NAME OF CANDIDATE");
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 420, 60));

        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel7.setText("ID");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 100));

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel1.setText("ADD CANDIDATE");
        jLabel1.setToolTipText("HEADING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 340, 70));

        post.setFont(new java.awt.Font("Poor Richard", 2, 36)); // NOI18N
        post.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Head_Boy", "Head_Girl", "deputy_head_boy", "Deputy_Head_Girl", "Cleanliness_IN_Charge", "Discipline_IN_Charge", "Sports_Captain" }));
        post.setToolTipText("POST");
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });
        getContentPane().add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 420, 70));

        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel2.setText("Name");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 100));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        cd1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        cd1.setText("Reset");
        cd1.setToolTipText("Reset");
        cd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd1ActionPerformed(evt);
            }
        });
        getContentPane().add(cd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 210, 60));

        cd2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        cd2.setText("ADD Candidate");
        cd2.setToolTipText("ADD CANDIDATE");
        cd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd2ActionPerformed(evt);
            }
        });
        getContentPane().add(cd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 210, 60));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel4.setText("Class");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 140, 70));

        Cls.setFont(new java.awt.Font("Poor Richard", 2, 36)); // NOI18N
        Cls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XII-Sci.", "XII-Comm.", "XI-Sci.", "XI-Comm." }));
        Cls.setSelectedIndex(-1);
        Cls.setToolTipText("CLASS");
        Cls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClsActionPerformed(evt);
            }
        });
        getContentPane().add(Cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 420, 70));

        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel5.setText("Post");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save user.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-530, -30, 1970, 786));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new Welcome_Screen().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postActionPerformed

    private void cd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd1ActionPerformed
ID.setText("");
        name.setText("");
post.setSelectedIndex(-1);
Cls.setSelectedIndex(-1);
// TODO add your handling code here:
    }//GEN-LAST:event_cd1ActionPerformed

    private void cd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd2ActionPerformed
              try{
Class.forName("java.sql.Driver");
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","") ;
        Statement stmt=con.createStatement();
        String Post=(String) post.getSelectedItem();
        String query;
        String vote,getCandidate;
        getCandidate="Select rowcount() from electiontb ";
       query = ("Insert into electiontb Values("+ID.getText() +",'"+name.getText()+"','"+post.getSelectedItem()+"','"+Cls.getSelectedItem()+"',0);");
     stmt.executeUpdate(query);
   stmt.close();
   con.close();
   JOptionPane.showMessageDialog(null,"SUCCEFULLY ADDED CANDIDATE");
}       catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
name.setText("");
post.setSelectedIndex(-1);
Cls.setSelectedIndex(-1);
cd1.doClick();
    }//GEN-LAST:event_cd2ActionPerformed

    private void ClsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClsActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Candidate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cls;
    private javax.swing.JTextField ID;
    private javax.swing.JButton cd1;
    private javax.swing.JButton cd2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> post;
    // End of variables declaration//GEN-END:variables
}
