
import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Candidates extends javax.swing.JFrame {

    /**
     * Creates new form Candidates
     */
    public Candidates() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Post_Title = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        post = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1386, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 280, 260, 90));

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton4.setText("Get Candidates");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 610, 380, 60));

        Post_Title.setFont(new java.awt.Font("Cambria", 1, 60)); // NOI18N
        Post_Title.setForeground(new java.awt.Color(255, 255, 255));
        Post_Title.setText("List Of Candidates");
        getContentPane().add(Post_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 570, 100));

        jButton3.setFont(new java.awt.Font("Poor Richard", 3, 36)); // NOI18N
        jButton3.setText("Delete Candidate");
        jButton3.setToolTipText("Delete Candidate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, -1, 60));

        tbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Post", "Class"
            }
        ));
        tbl.setRowHeight(40);
        jScrollPane2.setViewportView(tbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 1240, 320));

        post.setFont(new java.awt.Font("Poor Richard", 2, 36)); // NOI18N
        post.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Head_Boy", "Head_Girl", "Deputy_Head_Boy", "Deputy_Head_Girl", "Sports_captain", "Discipline_IN_Charge", "Cleanliness_IN_Charge", " " }));
        post.setSelectedIndex(-1);
        post.setToolTipText("post");
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });
        getContentPane().add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 400, 70));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton2.setText("Main Screen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 280, 60));

        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel5.setText("Select Post");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-2.psd.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1386, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new Welcome_Screen().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DefaultTableModel model=(DefaultTableModel)tbl.getModel();
int rno=tbl.getSelectedRow();
String Post=(String) post.getSelectedItem();
        try{
Class.forName("java.sql.Driver");
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","") ;
        
   Statement stmt=con.createStatement();
        String query,vote;
        query = ("Delete from Electiontb where ID="+model.getValueAt(rno, 0)+";");
       stmt.executeUpdate(query);
     model.setRowCount(0);
      
     String query1;
        query1 = ("Select * from Electiontb where Post='"+Post+"';");
      
        ResultSet hello;
      hello=stmt.executeQuery(query1);
    while(hello.next())
    { model.addRow(new Object[]{hello.getInt("ID"),hello.getString("Name"),hello.getString("Post"),hello.getString("Class")});
   
    } 
   
   stmt.close();
   con.close();
   JOptionPane.showMessageDialog(null,"Deleted Succesfully");
    


}       catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model=(DefaultTableModel)tbl.getModel();
        model.setRowCount(0);
        String Post=(String) post.getSelectedItem();
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","") ;

            Statement stmt=con.createStatement();
            String query;
            query = ("Select * from Electiontb where post='"+Post+"' order by ID; ");
            ResultSet hello;
            hello=stmt.executeQuery(query);
            while(hello.next())
            { model.addRow(new Object[]{hello.getInt("ID"),hello.getString("Name"),hello.getString("Post"),hello.getString("Class")});
            }

            stmt.close();
            con.close();
//            JOptionPane.showMessageDialog(null,"Printed Succesfully");

        }       catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);

        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Candidates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Post_Title;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> post;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
