/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class Deputy_Head_Boy extends javax.swing.JFrame {

    /**
     * Creates new form Head_boy
     */
    public Deputy_Head_Boy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        o1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        Post_Title = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HeadBoy");
        setBackground(new java.awt.Color(0, 153, 255));
        setPreferredSize(new java.awt.Dimension(1386, 796));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        o1.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        o1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ayush.png"))); // NOI18N
        o1.setText("Ayush Rana");
        o1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        o1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        o1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        o1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o1ActionPerformed(evt);
            }
        });
        getContentPane().add(o1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 400, 250));

        back.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 600, 200, 50));

        next.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        next.setMnemonic('N');
        next.setText("Next");
        next.setEnabled(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 120, 41));

        Post_Title.setFont(new java.awt.Font("Cambria", 1, 80)); // NOI18N
        Post_Title.setForeground(new java.awt.Color(255, 255, 255));
        Post_Title.setText("Deputy Head Boy");
        getContentPane().add(Post_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 720, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrival_4K_Motion_Background_Loop.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1970, 786));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
     this.setVisible(false);
new Post().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

back.setEnabled(true);
o1.setEnabled(true);
  
// TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void o1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o1ActionPerformed
try{
Class.forName("java.sql.Driver");
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","") ;
        Statement stmt=con.createStatement();
        String query;
        query = ("update electiontb  set votes=votes+1 where ID=his id ;");
        
        stmt.executeUpdate(query);
   stmt.close();
   con.close();
   o1.setEnabled(false);  
//JOptionPane.showMessageDialog(null,"aapka vote dal gaya hai,,doosre koo aane do");
}       catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            
        }        // TODO add your handling code here:
next.setEnabled(true);       // TODO add your handling code here:
    }//GEN-LAST:event_o1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deputy_Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Head_Boy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Post_Title;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton next;
    private javax.swing.JButton o1;
    // End of variables declaration//GEN-END:variables
}
