import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.String;
public class Edit_Candidate extends javax.swing.JFrame {

    
    public Edit_Candidate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */String dir;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        post = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Name = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Cls = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        cd2 = new javax.swing.JButton();
        cd1 = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel7.setText("ID No.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 70));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-2.psd.jpg"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 110));

        post.setFont(new java.awt.Font("Poor Richard", 2, 36)); // NOI18N
        post.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Head_Boy", "Head_Girl", "Deputy_HEad Boy", "Deputy_HEad Girl", "Cleaniness_IN-Charge", "Discipline_IN-Charge" }));
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });
        getContentPane().add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 220, 70));

        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel5.setText("Post");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 140, 70));

        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 180, 100));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton2.setText("Get Candidates");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 380, 60));

        Name.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 220, 60));

        ID.setEditable(false);
        ID.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 220, 60));

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel1.setText("Edit Candidate's Details");
        jLabel1.setToolTipText("HEADING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 380, 70));

        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton6.setText("Transfer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 380, 60));

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton3.setText("Main Screen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, 280, 60));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel4.setText("CLASS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 140, 70));

        Cls.setFont(new java.awt.Font("Poor Richard", 2, 36)); // NOI18N
        Cls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XII-Sci.", "XII-Comm.", "XI-Sci.", "XI-Comm." }));
        Cls.setSelectedIndex(-1);
        Cls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClsActionPerformed(evt);
            }
        });
        getContentPane().add(Cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 220, 70));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Post", "Class"
            }
        ));
        jScrollPane2.setViewportView(tbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 470, 280));

        cd2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        cd2.setText("Edit Candiate");
        cd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd2ActionPerformed(evt);
            }
        });
        getContentPane().add(cd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 210, 60));

        cd1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        cd1.setText("Reset");
        cd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd1ActionPerformed(evt);
            }
        });
        getContentPane().add(cd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 210, 60));

        lbl.setFont(new java.awt.Font("French Script MT", 0, 36)); // NOI18N
        lbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 280, 246));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit user.jpg"))); // NOI18N
        jLabel8.setPreferredSize(null);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-540, -50, 1970, 786));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 220, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
  /*Name.setText("");

 try{
Class.forName("java.sql.Driver");
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","") ;
        
   Statement stmt=con.createStatement();
        String query;
        query = ("Select Name from electiontb where post='"+post.getSelectedItem()+"';");
      ResultSet rs;
      rs=stmt.executeQuery(query);
    while(rs.next())
    { name.addItem(rs.getString("Name"));
    }
    
     rs.close();
        
   stmt.close();
   con.close();
  


}       catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            
        }  
    */         // TODO add your handling code here:
    }//GEN-LAST:event_postActionPerformed

    private void ClsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClsActionPerformed

    private void cd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd2ActionPerformed
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","") ;
            Statement stmt=con.createStatement();
            String query;
            query = ("Update Electiontb set NAME='" +Name.getText()+"',POST='"+post.getSelectedItem()+"', CLASS='"+Cls.getSelectedItem()+"' where ID="+ID.getText()+";");

            stmt.executeUpdate(query);
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"EDITED CANDIDATE'S DETAILS SUCCEFULLY");
jButton2.doClick();
        }       catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);

        }
        /*name.setText("");
        post.setSelectedIndex(-1);
        Cls.setSelectedIndex(-1);
        S_name.setText("");
        directory.setText(" ");

            Frame window= new Head_boy();
        window.setSize(600, 400);
        window.setLayout(null);
        JButton b4 = new JButton(name.getText());
        b4.setLocation(10, 10);
        b4.setSize(100, 26);
        b4.setIcon(new ImageIcon(dir));
        window.add(b4);
        window.setVisible(true);*/
    }//GEN-LAST:event_cd2ActionPerformed

    private void cd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd1ActionPerformed
        Name.setText("");
        post.setSelectedIndex(-1);
        Cls.setSelectedIndex(-1);
ID.setText(" ");// TODO add your handling code here:
    }//GEN-LAST:event_cd1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 DefaultTableModel model=(DefaultTableModel)tbl.getModel();
model.setRowCount(0);
 String Post=(String) post.getSelectedItem();
        try{
Class.forName("java.sql.Driver");
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","") ;
        
   Statement stmt=con.createStatement();
        String query;
        query = ("Select * from Electiontb; ");
      ResultSet hello;
      hello=stmt.executeQuery(query);
    while(hello.next())
    { model.addRow(new Object[]{hello.getInt("ID"),hello.getString("Name"),hello.getString("Post"),hello.getString("Class")});
 }
    
        
   stmt.close();
   con.close();


}       catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
        new Welcome_Screen().setVisible(true);
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

     ID.setText("");
  
int selected_row=tbl.getSelectedRow();
 DefaultTableModel model=(DefaultTableModel)tbl.getModel();
//int id=Integer.parseInt((String) model.getValueAt(selected_row,0));
 ID.setText(""+ model.getValueAt(selected_row,0) );
 Name.setText((String) model.getValueAt(selected_row,1));
 post.setSelectedItem(model.getValueAt(selected_row,2));
 Cls.setSelectedItem(model.getValueAt(selected_row,3));
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Candidate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cls;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JButton cd1;
    private javax.swing.JButton cd2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl;
    private javax.swing.JComboBox<String> post;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
