/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class Head_Boy extends javax.swing.JFrame {

    /**
     * Creates new form Head_boy
     */
    public Head_Boy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bb = new javax.swing.JButton();
        next = new javax.swing.JButton();
        Post_Title = new javax.swing.JLabel();
        o = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HeadBoy");
        setBackground(new java.awt.Color(0, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bb.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        bb.setText("Back");
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        getContentPane().add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 150, 41));

        next.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        next.setMnemonic('z');
        next.setText("Next");
        next.setEnabled(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 120, 41));

        Post_Title.setFont(new java.awt.Font("Cambria", 1, 80)); // NOI18N
        Post_Title.setForeground(new java.awt.Color(255, 255, 255));
        Post_Title.setText("Head Boy");
        getContentPane().add(Post_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 440, 100));

        o.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        o.setIcon(new javax.swing.ImageIcon(getClass().getResource("/don bhai.png"))); // NOI18N
        o.setText("Sudhanshu Ranjan");
        o.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        o.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        o.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });
        getContentPane().add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, 270));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrival_4K_Motion_Background_Loop.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1970, 786));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed

this.setVisible(false);
new Post().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bbActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
bb.setEnabled(false);

   o.setEnabled(true);
   
// TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
try{
Class.forName("java.sql.Driver");
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","") ;
        Statement stmt=con.createStatement();
        String query;
        query = ("update electiontb  set votes=votes+1 where ID=his id ;");
        stmt.executeUpdate(query);
   stmt.close();
   con.close();
  
   o.setEnabled(false);

}       catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            
        }
next.setEnabled(true);
bb.setEnabled(true);
    }//GEN-LAST:event_oActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Head_Boy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Post_Title;
    private javax.swing.JButton bb;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton next;
    private javax.swing.JButton o;
    // End of variables declaration//GEN-END:variables
}
