/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class Head_Girl extends javax.swing.JFrame {

    /**
     * Creates new form Head_boy
     */
    public Head_Girl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        C2 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        Post_Title = new javax.swing.JLabel();
        C1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HeadBoy");
        setBackground(new java.awt.Color(0, 153, 255));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        C2.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/harshita.png"))); // NOI18N
        C2.setText("Harshita Mishra");
        C2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        C2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        C2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 480, 260));

        back.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 280, 41));

        next.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        next.setMnemonic('N');
        next.setText("Next");
        next.setEnabled(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 120, 41));

        Post_Title.setFont(new java.awt.Font("Cambria", 1, 80)); // NOI18N
        Post_Title.setForeground(new java.awt.Color(255, 255, 255));
        Post_Title.setText("Head Girl");
        getContentPane().add(Post_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 440, 100));

        C1.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shivalika.png"))); // NOI18N
        C1.setText("Shivalika Chaturvedi");
        C1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        C1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        C1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        C1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 500, 260));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrival_4K_Motion_Background_Loop.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1970, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
  
{this.setVisible(false);
new Post().setVisible(true);}
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
   C1.setEnabled(true);
back.setEnabled(true);
C2.setEnabled(true);
 
// TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
try{
Class.forName("java.sql.Driver");
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","") ;
        Statement stmt=con.createStatement();
        String query;
        query = ("update electiontb  set votes=votes+1 where ID=his id ;");
        stmt.executeUpdate(query);
   stmt.close();
   con.close();
  
   C1.setEnabled(false);
  
C2.setEnabled(false);
 
//JOptionPane.showMessageDialog(null,"aapka vote dal gaya hai,,doosre koo aane do");
}       catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            
        }
next.setEnabled(true);

// TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
try{
Class.forName("java.sql.Driver");
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","") ;
        Statement stmt=con.createStatement();
        String query;
        query = ("update electiontb  set votes=votes+1 where ID=his id ;");
        stmt.executeUpdate(query);
   stmt.close();
   con.close();
   
C1.setEnabled(false);
C2.setEnabled(false);
 //JOptionPane.showMessageDialog(null,"aapka vote dal gaya hai,,doosre koo aane do");
}       catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            
        }        // TODO add your handling code here:
next.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_C2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Head_Boy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JLabel Post_Title;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
