
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form First_Window
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Login_Panel = new javax.swing.JPanel();
        tgb = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        u_name = new javax.swing.JTextField();
        pswd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Page");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        jButton1.setFont(new java.awt.Font("Poor Richard", 0, 48)); // NOI18N
        jButton1.setText("Let's Go  ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, 360, 80));

        Login_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Login_Panel.setBorder(new javax.swing.border.MatteBorder(null));
        Login_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tgb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        tgb.setContentAreaFilled(false);
        tgb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbActionPerformed(evt);
            }
        });
        Login_Panel.add(tgb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 60, 60));

        jLabel6.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jLabel6.setText("Password");
        Login_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 200, 80));

        jLabel7.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jLabel7.setText("Enter User Name");
        Login_Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 420, 80));

        u_name.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        u_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_nameActionPerformed(evt);
            }
        });
        Login_Panel.add(u_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 500, 80));

        pswd.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        Login_Panel.add(pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 500, 90));

        getContentPane().add(Login_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 580, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1386, 768));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String pass = new String (pswd.getPassword());
String welspun="WELSPUN";
        if(u_name.getText().equals("WVM")) 
{  if(pass.equals(welspun))
   {this.setVisible(false);
   new Welcome_Screen().setVisible(true);}

    else {JOptionPane.showMessageDialog(null,"You have entered WRONG PASSWORD. Please enter the CORRECT PASSWORD");
             pswd.setText("");}}
        else {JOptionPane.showMessageDialog(null,"You have entered WRONG User name. Please enter the CORRECT User name");
         if(pass.equals(welspun))
          {this.setVisible(false);
          new Welcome_Screen().setVisible(true);}

    else {JOptionPane.showMessageDialog(null,"You have entered WRONG PASSWORD. Please enter the CORRECT PASSWORD");
             pswd.setText("");}
        u_name.setText("");}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tgbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbActionPerformed
if (tgb.isSelected()) 
{pswd.setEchoChar((char)0);}
else if(tgb.isSelected()==false)
{pswd.setEchoChar('*');}

// TODO add your handling code here:
    }//GEN-LAST:event_tgbActionPerformed

    private void u_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JToggleButton tgb;
    private javax.swing.JTextField u_name;
    // End of variables declaration//GEN-END:variables
}
