
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Post extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Post() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Post_Title = new javax.swing.JLabel();
        o1 = new javax.swing.JButton();
        o2 = new javax.swing.JButton();
        o3 = new javax.swing.JButton();
        o4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        o5 = new javax.swing.JButton();
        o6 = new javax.swing.JButton();
        o7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Post_Title.setFont(new java.awt.Font("Cambria", 1, 90)); // NOI18N
        Post_Title.setForeground(new java.awt.Color(255, 255, 255));
        Post_Title.setText("Posts");
        getContentPane().add(Post_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 440, 100));

        o1.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        o1.setText("Sports Captain");
        o1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        o1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        o1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o1ActionPerformed(evt);
            }
        });
        getContentPane().add(o1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 440, 120));

        o2.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        o2.setText("Deputy Head Boy");
        o2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        o2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        o2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o2ActionPerformed(evt);
            }
        });
        getContentPane().add(o2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 530, 120));

        o3.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        o3.setText("Cleanliness In-Charge");
        o3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        o3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        o3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o3ActionPerformed(evt);
            }
        });
        getContentPane().add(o3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 530, 120));

        o4.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        o4.setText("Head Boy");
        o4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        o4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        o4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o4ActionPerformed(evt);
            }
        });
        getContentPane().add(o4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 530, 120));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton2.setText("Main Screen");
        jButton2.setToolTipText("MAIN SCREEN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 240, 60));

        o5.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        o5.setText("Head Girl");
        o5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        o5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        o5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o5ActionPerformed(evt);
            }
        });
        getContentPane().add(o5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 520, 120));

        o6.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        o6.setText("Discipline In-Charge");
        o6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        o6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        o6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o6ActionPerformed(evt);
            }
        });
        getContentPane().add(o6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 530, 120));

        o7.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        o7.setText("Deputy Head Girl");
        o7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        o7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        o7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o7ActionPerformed(evt);
            }
        });
        getContentPane().add(o7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 530, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrival_4K_Motion_Background_Loop.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1970, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void o1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o1ActionPerformed
this.setVisible(false);    
new Sports_Captain().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_o1ActionPerformed

    private void o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o2ActionPerformed
this.setVisible(false);    
new Deputy_Head_Boy().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_o2ActionPerformed

    private void o3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o3ActionPerformed
this.setVisible(false);    
new Cleanliness_In_Charges().setVisible(true); 
                // TODO add your handling code here:
    }//GEN-LAST:event_o3ActionPerformed

    private void o4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o4ActionPerformed
this.setVisible(false);    
new Head_Boy().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_o4ActionPerformed

    private void o5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o5ActionPerformed
this.setVisible(false);    
new Head_Girl().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_o5ActionPerformed

    private void o6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o6ActionPerformed
this.setVisible(false);    
new Discipline_In_Charges().setVisible(true);
               // TODO add your handling code here:
    }//GEN-LAST:event_o6ActionPerformed

    private void o7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o7ActionPerformed
this.setVisible(false);    
new Deputy_Head_Girl().setVisible(true);
               // TODO add your handling code here:
    }//GEN-LAST:event_o7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new Welcome_Screen().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Post().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Post_Title;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton o1;
    private javax.swing.JButton o2;
    private javax.swing.JButton o3;
    private javax.swing.JButton o4;
    private javax.swing.JButton o5;
    private javax.swing.JButton o6;
    private javax.swing.JButton o7;
    // End of variables declaration//GEN-END:variables
}
